server:
  port: 9000

security:
  user:
    password: password

zuul:
  routes:
    springbox-catalog: /catalog/**
    springbox-reviews: /reviews/**
    springbox-recommendations: /recommendations/**
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user

spring:
  oauth2:
    sso:
      home:
        secure: false
        path: /,/**/*.html
#    client:
#      accessTokenUri: http://localhost:9999/uaa/oauth/token
#      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
#      clientId: acme
#      clientSecret: acmesecret
#    resource:
#      userInfoUri: http://localhost:9999/uaa/user

logging:
  level:
    org.springframework.security: INFO
    org.springframework.cloud.netflix: INFO
    com.netflix.zuul: INFO
    io.springbox.apigateway: DEBUG

---

spring:
  profiles: cloud

zuul:
  routes:
    user:
      url: ${vcap.services.${spring.oauth2.sso.serviceId:sso}.credentials.userInfoUri}
